Repository openNAMU/openNAMU, pull requests merged in 2022-02, with the labels that each got.

#1332 문단 링크를 위한 id 정정
  views/main_css/js/render_wiki.js
Labels: A 버그 (Bug), B 일반 (Normal)

#1346 언어 설정에 따른 언어 태그 구문 추가
  lang/en-US.json
  lang/ko-KR.json
  views/ringo/index.html
  views/tenshi/index.html
Labels: A 개선 (Improve), C 언어 (Language)

#1354 리다이렉트 수정
  route/login_register_submit.py
Labels: C 기능 (Function), A 개선 (Improve)

#1359 사용자 지정 404 페이지가 HTTP 상태 코드 404를 반환하도록 수정
  route/main_error_404.py
Labels: A 버그 (Bug), B 자잘함 (Petty)
