Repository openNAMU/openNAMU, pull requests merged in 2024-11, with the labels that each got.

#2447 fetch 요청 확인 후 실패하면 에러 메시지 출력
  views/main_css/js/func/func.js
Labels: A 개선 (Improve), C 코드 (Code)

#2451 feat #2449: 회원 가입 시 ID, PW 중복 방지 기능 추가
  lang/en-US.json
  lang/ko-KR.json
  route/login_register.py
  route/tool/func.py
Labels: C 기능 (Function), A 개선 (Improve)

#2452 위키 렌더링 엔진에 [[../하위주소]] 와 같은 상대 내부 링크 지원 추가
  route/tool/func_render_namumark.py
Labels: A 개선 (Improve), C 렌더러 (Renderer)
